version: '3.9'

services:
  kratos-migrate:
    depends_on:
      - postgresd
    image: oryd/kratos:v0.6.3-alpha.1
    environment:
      - DSN=${DB_URL}
    volumes:
      - type: bind
        source: ./.kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos-cli:
    image: oryd/kratos:v0.6.3-alpha.1
    environment:
      - KRATOS_ADMIN_URL=http://kratos:4434

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.6.3-alpha.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    environment:
      - DSN=${DB_URL}
      - LOG_LEVEL=trace
    volumes:
      - type: bind
        source: ./.kratos
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    restart: unless-stopped
    networks:
      - intranet

  postgresd:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
    networks:
      - intranet

networks:
  intranet:
