version: '3.7'

services:
  kratos-migrate:
    depends_on:
      - postgresd
    image: oryd/kratos:v0.6.3-alpha.1
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./.kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  kratos-cli:
    image: oryd/kratos:v0.6.3-alpha.1
    environment:
      - KRATOS_ADMIN_URL=http://kratos:4434

  kratos:
    depends_on:
      - mailslurper
      # - oathkeeper
      - postgresd
    image: oryd/kratos:v0.6.3-alpha.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    volumes:
      - type: bind
        source: ./.kratos
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    restart: unless-stopped

  postgresd:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
